var puns = [
    'Time flies like an arrow. Fruit flies like a banana.',
    'Show me a piano falling down a mineshaft and I\'ll show you A-flat minor.',
    'To write with a broken pencil is pointless.',
    'A bicycle can\'t stand on its own because it is two-tired.',
    'Those who get too big for their britches will be exposed in the end.',
    'When a clock is hungry it goes back four seconds.',
    'A chicken crossing the road is poultry in motion.',
    'If you don\'t pay your exorcist you get repossessed.',
    'What\'s the definition of a will? It\'s a dead giveaway.',
    'The man who fell into an upholstery machine is fully recovered.',
    'Every calendar\'s days are numbered.',
    'Bakers trade bread recipes on a knead to know basis.',
    'When the electricity went off during a storm at a school the students were de-lighted.',
    'I used to be a tap dancer until I fell in the sink.',
    'He wears glasses during math because it improves division.',
    'She was only a whisky maker but he loved her still.',
    'She had a boyfriend with a wooden leg, but broke it off.',
    'Those who jump off a Paris bridge are in Seine.',
    'It wasn\'t school John disliked it was just the principal of it.',
    'It\'s better to love a short girl than not a tall.',
    'There was once a cross-eyed teacher who couldn\'t control his  pupils.',
    'A grenade thrown into a kitchen in France would result in Linoleum Blownapart.',
    'A boiled egg in the morning is hard to beat.',
    'The one who invented the door knocker got a No-bell prize.',
    'Old power plant workers never die they just de-generate.',
    'There was a ghost at the hotel, so they called for an inn spectre.',
    'With her marriage she got a new name and a dress.',
    'The short fortune-teller who escaped from prison was a small medium at large.',
    'Some Spanish government employees are Seville servants.',
    'He drove his expensive car into a tree and found out how the Mercedes bends.',
    'Show me someone in denial and I\'ll show you a person in Egypt up to their ankles.',
    'Two peanuts were walking in a tough neighborhood and one of them was a-salted.',
    'When cannibals ate a missionary they got a taste of religion.',
    'When an actress saw her first strands of gray hair she thought she\'d dye.',
    'He often broke into song because he couldn\'t find the key.',
    'Marathon runners with bad footwear suffer the agony of defeat.',
    'Driving on so many turnpikes was taking its toll.',
    'To some - marriage is a word ... to others - a sentence.',
    'Old lawyers never die they just lose their appeal.',
    'In democracy its your vote that counts. In feudalism its your count that votes.',
    'It was an emotional wedding. Even the cake was in tiers.',
    'Old skiers never die -- they just go down hill.',
    'A cardboard belt would be a waist of paper.',
    'Local Area Network in Australia: the LAN down under.',
    'When the TV repairman got married the reception was excellent.',
    'An office with many people and few electrical outlets could be in for a power struggle.',
    'How do you make antifreeze? Steal her blanket.',
    'A small boy swallowed some coins and was taken to a hospital. When his grandmother telephoned to ask how he was a nurse said \'No change yet\'.',
    'A pediatrician is a doctor of little patients.',
    'Nylons give women a run for their money.',
    'Talking to her about computer hardware I make my mother board.',
    'Ancient orators tended to Babylon.',
    'The best way to stop a charging bull is to take away his credit card.',
    'If you give some managers an inch they think they\'re a ruler.',
    'Two silk worms had a race. They ended up in a tie.',
    'He had a photographic memory that was never developed.',
    'Old burglars never die they just steal away.',
    'A lawyer for a church did some cross-examining.',
    'Chronic illegal parkers suffer from parking zones disease.',
    'Some people don\'t like food going to waist..', 
    'A cannibal\'s favourite game is \'swallow the leader.',
    'You feel stuck with your debt if you can\'t budge it.',
    'Girls who don\'t get asked out as often as their friends could feel out-dated.',
    'We were so poor when I was growing up we couldn\'t even afford to pay attention.',
    'A pet store had a bird contest with no perches necessary.',
    'A backwards poet writes inverse.',
    'If a lawyer can be disbarred can a musician be denoted or a model deposed?',
    'Once you\'ve seen one shopping center you\'ve seen a mall.',
    'When the smog lifts in Los Angeles, U C L A.',
    'A plateau is a high form of flattery.',
    'When chemists die, we barium.',
    'A long knife has been invented that cuts four loaves of bread at a time called a four loaf cleaver.',
    'When the wheel was invented, it caused a revolution.',
    'Two robbers with clubs went golfing, but they didn\'t play the fairway.',
    'Seven days without a pun makes one weak.',
    'A circus lion won\'t eat clowns because they taste funny.',
    'A toothless termite walked into a tavern and said, "Is the bar tender here?"',
    'Did you hear about the fire at the circus? The heat was intense.',
    'A tattoo artist has designs on his clients.',
    'Santa\'s helpers are subordinate clauses.',
    'A lot of money is tainted. It taint yours and it taint mine.',
    'When they bought a water bed, the couple started to drift apart.',
    'What you seize is what you get.',
    'Gardeners always know the ground rules.',
    'Some people\'s noses and feet are build backwards: their feet smell and their noses run.', 
    'Two banks with different rates have a conflict of interest.',
    'A successful diet is the triumph of mind over platter.',
    'What do you call cheese that is not yours? Nacho Cheese.',   
    'When a new hive is done bees have a house swarming party.',    
    'Looting a drugstore is called Pillaging.',    
    'Never lie to an x-ray technician. They can see right through you.',    
    'Old programmers never die, they just can\'t C as well.',    
    'A music store had a small sign which read: Bach in a Minuet.',    
    'Long fairy tales have a tendency to dragon.',    
    'Visitors to Cuba are usually Havana good time.',    
    'A bachelor is a guy who is footloose and fiancée-free.',    
    'A ditch digger was entrenched in his career.',    
    'A girl and her boyfriend went to a party as a barcode. They were an item.',
    'A criminal\'s best asset is his lie ability.',
    'Dad, did you get a haircut? No I got them all cut.',
    'What do you call a Mexican who has lost his car? Carlos.',
    'Dad, can you put my shoes on? No, I don’t think they’ll fit me.',
    'Can I watch the TV? Dad: Yes, but don’t turn it on.',
    'I would avoid the sushi if I was you. It’s a little fishy.',
    'What do you call a fake noodle? An Impasta.',
    'You know, people say they pick their nose, but I feel like I was just born with mine.',
    '“Every time I hurt myself, even to this day, my dad says, ‘The good news is..it’ll feel better when it quits hurting.\'”',
    'What’s brown and sticky? A stick.',
    'Want to hear a joke about paper? Nevermind it’s tearable.',
    'Did you hear about the restaurant on the moon? Great food, no atmosphere.',
    '“I’ll call you later!”- “Please don’t do that. I’ve always asked you to call me Dad!”',
    'Q: Why did the cookie cry? A: Because his father was a wafer so long!',
    'What did the mountain climber name his son? Cliff.',
    'This graveyard looks overcrowded. People must be dying to get in there.',
    '“My dad literally told me this one last week: ‘Did you hear about the guy who invented Lifesavers? They say he made a mint.’”',
    '“Whenever the cashier at the grocery store asks my dad if he would like the milk in a bag he replies, ‘No, just leave it in the carton!’”',
    'I got so angry the other day when I couldn’t find my stress ball.',
    'If I had a dime for every book I’ve ever read, I’d say: “Wow, that’s coincidental.”',
    'I’m not indecisive. Unless you want me to be.',
    'How many apples grow on a tree? All of them.',
    'How does a penguin build it’s house? Igloos it together.',
    '“Me: ‘Dad, make me a sandwich!’ Dad: ‘Poof, You’re a sandwich!’”',
    '“I heard there was a new store called Moderation. They have everything there',
    'A steak pun is a rare medium well done.',
    '“How can you tell if a ant is a boy or a girl? They’re all girls, otherwise they’d be uncles.”',
    'Milk is also the fastest liquid on earth – its pasteurized before you even see it',
    '“What’s Forrest Gump’s password? 1forrest1”',
    'The only thing worse than having diarrhea is having to spell it.',
    'I asked my friend to help me with a math problem. He said: “Don’t worry; this is a piece of cake.” I said: “No, it’s a math problem.”',
    'I keep trying to lose weight, but it keeps finding me.',
    'I don’t play soccer because I enjoy the sport. I’m just doing it for kicks.',
    'Did I tell you the time I fell in love during a backflip? I was heels over head.',
    'I used to work in a shoe recycling shop. It was sole destroying.',
    'Why do you never see elephants hiding in trees? Because they’re so good at it.',
    'Where did the one-legged waitress work? IHOP!',
    'What happened when the two antennas got married? Well, the ceremony was kinda boring, but the reception was great!',
    'What did one snowman say to the other one?  “Do you smell carrots?”',
    'How do you make a tissue dance?  You put a little boogie in it!',
    'Why did the blonde stare at the orange juice container?  It said concentrate!',
    'If your nose runs and your feet smell, you are built upside down!',
    'I went to buy some camouflage trousers the other day, but I couldn’t find any.',
    'Q: How do you organize an outer space party? A: You planet.',
    'Q: What do you call a belt with a watch on it? A: A waist of time.',
    'What kind of shoes does a thief wear? Sneakers',
    'A jumper cable walks into a bar. The bartender says, “I’ll serve you, but don’t start anything.”',
    'An invisible man marries an invisible woman. The kids were nothing to look at either.',
    'I went to a seafood disco last week… and pulled a mussel.',
    'Did you hear about the man who stole a calendar? He got 12 months.',
    'A man woke up in a hospital after a serious accident. He shouted, Doctor, doctor, I can’t feel my legs!” The doctor replied, “I know you can’t I’ve cut off your arms!”',
    'Do you know where you can get chicken broth in bulk? The stock market.',
    'What did the ocean say to the shore? Nothing, it just waved.',
    '“What’s ET short for? Because he’s only got little legs.”',
    'Why do crabs never give to charity? Because they’re shellfish.',
    'What do you call an Argentinian with a rubber toe? Roberto',
    '“What do you call a man with no nose and no body? Nobody nose.”',
    'I cut my finger chopping cheese, but I think that I may have greater problems.',
    'What do you call a fish with no eyes? A fshhhh.',
    '“What do you call a man with no arms and no legs lying in front of your door? Matt.”',
    'My cat was just sick on the carpet, I don’t think it’s feline well.',
    'I dreamed about drowning in an ocean made out of orange soda last night. It took me a while to work out it was just a Fanta sea.',
    'Without geometry life is pointless.',
    'A termite walks into a bar and asks “Is the bar tender here?”',
    'I gave all my dead batteries away today… Free of charge.',
    'I needed a password eight characters long so I picked Snow White and the Seven Dwarfs.',
    'I am terrified of elevators. I’m going to start taking steps to avoid them.',
    'What’s the advantage of living in Switzerland? Well, the flag is a big plus.',
    'Why did the octopus beat the shark in a fight? Because it was well armed.',
    'A red and a blue ship have just collided in the Caribbean. Apparently the survivors are marooned.',
    'I’ve deleted the phone numbers of all the Germans I know from my mobile phone. Now it’s Hans free.',
    'Last night me and my girlfriend watched three DVDs back to back. Luckily I was the one facing the TV.',
    'Q: What did daddy spider say to baby spider? A: You spend too much time on the web.',
    'How much does a hipster weigh? An instagram.',
    'What do you call a group of killer whales playing instruments? An Orca-stra.',
    'Why was the big cat disqualified from the race? Because it was a cheetah.',
    'Bicycles can’t stand on their own, they’re two tired.',
    'Just watched a documentary about beavers… It was the best damn program I’ve ever seen.',
    'Breaking news! Energizer Bunny arrested – charged with battery',
    '“How do you make holy water? You boil the hell out of it.”',
    'A Sandwich walks into a bar, the bartender says “Sorry, we don’t serve food here”',
    '“Doctor, I’ve broken my arm in several places” Doctor “Well don’t go to those places.”',
    'I’m on a whiskey diet. I’ve lost three days already.',
    '“Why did the Clydesdale give the pony a glass of water?', 'Because he was a little horse!”',
    'There’s a new type of broom out, it’s sweeping the nation.',
    'Atheism is a non-prophet organisation.',
    'Slept like a log last night … woke up in the fireplace.',
    '“We were getting fast food when the lady at the window said, ‘Any condiments?’ My dad responded, ‘Compliments? You look very nice today!’”',
    'What cheese can never be yours? Nacho cheese.',
    'A police officer caught two kids playing with a firework and a car battery. He charged one and let the other one off.',
    'I’m reading a book on the history of glue – can’t put it down.',
    'Did you hear about the kidnapping at school? It’s fine, he woke up.',
    'I went to the zoo the other day, there was only one dog in it. It was a shitzu.',
    'What did the daddy tomato say to the baby tomato? A: catch up!',
    'Q: What’s 50 Cent’s name in Zimbabwe? A: 400 Million Dollars.',
    'Q: What did baby corn say to mama corn? A: Where’s popcorn?',
    'What do you call a cow with no legs? Ground beef.',
    'What did the Buffalo say to his little boy when he dropped him off at school? Bison.',
    'So a duck walks into a pharmacy and says “Give me some chap-stick… and put it on my bill”',
    'Why did the scarecrow win an award? Because he was outstanding in his field.',
    'Why did the girl smear peanut butter on the road? To go with the traffic jam.',
    'Why does a chicken coop only have two doors? Because if it had four doors it would be a chicken sedan.',
    'Why don’t seagulls fly over the bay? Because then they’d be bay-gulls!',
    'Two peanuts were walking down the street. One was a salted.',
    'What do you do when a blonde throws a grenade at you? Pull the pin and throw it back.',
    'How do you make a hankie dance? Put a little boogie in it.',
    'Where does batman go to the bathroom? The batroom.',
    'What’s the difference between an African elephant and an Indian elephant? About 5000 miles',
    'I’m on a seafood diet… I see food and I eat it.',
    'A man walks into a bar and orders helicopter flavor chips. The barman replies “sorry mate we only do plain”',
    ': Commissar! Commissar! The troops are revolting! Commissar: Well, you’re pretty repulsive yourself.',
    'What do you call a sheep with no legs? A cloud.',
    'I knew I shouldn’t have ate that seafood. Because now I’m feeling a little… Eel',
    'What did the 0 say to the 8? Nice belt.',
    'Why are skeletons so calm? Because nothing gets under their skin.',
    'Why don’t skeletons ever go trick or treating? Because they have nobody to go with.',
    'Why do scuba divers fall backwards into the water? Because if they fell forwards they’d still be in the boat.',
    'Have you ever heard of a music group called Cellophane? They mostly wrap.',
    'What kind of magic do cows believe in? MOODOO.',
    'Why does Superman gets invited to dinners? Because he is a Supperhero.',
    '“Hold on, I have something in my shoe”  “I’m pretty sure it’s a foot”',
    'Dad I’m hungry … “Hi hungry” I’m dad',
    'When phone ringing Dad says ‘If it’s for me don’t answer it.',
    '“I asked my dad for his best dad joke and he said, ‘You.’”',
    'Where’s the bin? Dad: I haven’t been anywhere!'
]

var thepun = '';

function generatePun() {
    var randomNumber = Math.random() * puns.length;
    var randomWhole = Math.floor(randomNumber);
    document.getElementById('punDisplay').innerHTML = puns[randomWhole]; 
    thepun = puns[randomWhole];
}

function share() {
    var text = thepun;
    var url = "www.github.com/athiyadeviyani";
    window.open('http://twitter.com/share?url='+encodeURIComponent(url)+'&text='+encodeURIComponent(text), '', 'left=0,top=0,width=550,height=450,personalbar=0,toolbar=0,scrollbars=0,resizable=0');
}

var siteWidth = 1280;
var scale = screen.width /siteWidth

document.querySelector('meta[name="viewport"]').setAttribute('content', 'width='+siteWidth+', initial-scale='+scale+'')
